owner: faisalaffan
repo: upptime
user-agent: faisalaffan

sites:
  - name: Faisal Affan Labs (Showcase)
    url: https://showcase.faisalaffan.com

  - name: Ragi Instant Web
    url: https://ragi-instant.vercel.app

  - name: Ragi Instant API
    url: https://ragi-instant.vercel.app/api/health

  - name: Fowcuzz Landing
    url: https://fowcuzz.com

assignees:
  - faisalaffan

status-website:
  baseUrl: /upptime
  name: Faisal Affan Labs Status
  navbar:
    - title: Status
      href: /
    - title: Showcase
      href: https://showcase.faisalaffan.com

workflowSchedule:
  uptime: "*/5 * * * *"
